USE COMPANY;
/*Q5*/

/*FINDING THE MANAGERS FIRST*/

SELECT E.FNAME, E.LNAME 
FROM 
	EMPLOYEES E, DEPARTMENTS D
WHERE
	E.SSN = D.MGRSSN;

/*MANAGERS WHO HAVE DEPENDENTS FIRST, TO HELP ME UNDERSTAND*/


/*EMPLOYEES THAT DO NOT HAVE DEPENDENTS TO HELP ME UNDERSTAND*/
SELECT M.FNAME, M.LNAME
FROM 
	EMPLOYEES M
WHERE
	M.SSN NOT IN (SELECT D.ESSN FROM DEPENDENTS D);

/*THIS TOOK A WHILE TO FIGURE OUT! HAVING MULTIPLE IN AND NOT INS */
SELECT M.FNAME, M.LNAME
FROM 
	EMPLOYEES M
WHERE
	M.SSN IN (SELECT D.MGRSSN FROM DEPARTMENTS D)
	AND
	M.SSN NOT IN (SELECT E.ESSN FROM DEPENDENTS E);
	
	